version: '2'

services:
  web:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  api:
    image: 'react-docker-server'
    ports:
      - '3001:3001'

